// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReviewAndRatingService.Data;

#nullable disable

namespace ReviewAndRatingService.Migrations
{
    [DbContext(typeof(ReviewContext))]
    [Migration("20241202094413_initial-migrationnn")]
    partial class initialmigrationnn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReviewAndRatingService.Model.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Great product!",
                            CreatedAt = new DateTime(2024, 12, 2, 9, 44, 13, 115, DateTimeKind.Utc).AddTicks(88),
                            Rating = 5,
                            ReviewerName = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Not bad.",
                            CreatedAt = new DateTime(2024, 12, 2, 9, 44, 13, 115, DateTimeKind.Utc).AddTicks(337),
                            Rating = 3,
                            ReviewerName = "Jane Smith"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
