// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingBasket.DbContexts;

#nullable disable

namespace ShoppingBasket.Migrations
{
    [DbContext(typeof(ShoppingBasketDbContext))]
    [Migration("20250108082008_2nit")]
    partial class _2nit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShoppingBasket.Models.BasketLine", b =>
                {
                    b.Property<Guid>("BasketLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ShoppingBasketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ShoppingBaskettShoppingBasketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BasketLineId");

                    b.HasIndex("ShoppingBasketId");

                    b.HasIndex("ShoppingBaskettShoppingBasketId");

                    b.ToTable("BasketLines");
                });

            modelBuilder.Entity("ShoppingBasket.Models.ShoppingBaskett", b =>
                {
                    b.Property<Guid>("ShoppingBasketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShoppingBasketId");

                    b.ToTable("ShoppingBaskets");
                });

            modelBuilder.Entity("ShoppingBasket.Models.BasketLine", b =>
                {
                    b.HasOne("ShoppingBasket.Models.ShoppingBaskett", null)
                        .WithMany()
                        .HasForeignKey("ShoppingBasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoppingBasket.Models.ShoppingBaskett", null)
                        .WithMany("BasketLines")
                        .HasForeignKey("ShoppingBaskettShoppingBasketId");
                });

            modelBuilder.Entity("ShoppingBasket.Models.ShoppingBaskett", b =>
                {
                    b.Navigation("BasketLines");
                });
#pragma warning restore 612, 618
        }
    }
}
