apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-basket
  namespace: ecommerce
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shopping-basket
  template:
    metadata:
      labels:
        app: shopping-basket
    spec:
      containers:
      - name: shopping-basket
        image: win10acr.azurecr.io/ecommerce-marketplace/shopping-basket:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-basket
  namespace: ecommerce
spec:
  type: ClusterIP
  selector:
    app: shopping-basket
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
