using Microsoft.Extensions.Options;
using PaymentService.Model;
using Stripe;
using System.Threading.Tasks;

namespace PaymentService.Services
{
    public class StripePaymentService : IPaymentService
    {
        private readonly StripeSettings _stripeSettings;

        public StripePaymentService(IOptions<StripeSettings> stripeSettings)
        {
            _stripeSettings = stripeSettings.Value;
            StripeConfiguration.ApiKey = _stripeSettings.SecretKey;
        }

        public async Task<Payment> ProcessPayment(Payment payment)
        {
            var options = new ChargeCreateOptions
            {
                Amount = (long)(payment.Amount * 100), // Amount in cents
                Currency = payment.Currency,
                Description = $"Order ID: {payment.OrderId}",
                Source = payment.TransactionId // This should be a token generated by Stripe.js on the client side
            };

            var service = new ChargeService();
            Charge charge = await service.CreateAsync(options);

            payment.Status = charge.Status;
            payment.TransactionId = charge.Id;

            return payment;
        }
    }
}
